### PR TITLE
Enviroment variables support

### LINKED ISSUE #10: Support for setting environment variables
VSC's [API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Terminal) supports setting environment variables, we should also support them.

### PR DESCRIPTION
**Pull request by M-Zuber**
Can set environment variables to be applied to a specific terminal, or globally to any terminal opened through the extension
fixes #10

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Thanks! I like the idea of also supporting global env variables. I'm going to rewrite this a bit though before publishing it.

**Comment by M-Zuber** [comment]
My pleasure

> I'm going to rewrite this a bit though before publishing it.

Of course! I will try and pay attention though, so next time you hopefully won't need to 😄

**Comment by fabiospampinato** [comment]
Published in v1.9.0, check out my [commit](https://github.com/fabiospampinato/vscode-terminals/commit/fe62880c9dff220d6bc80b55939dfd06154fced0).

Notable changes:
- I had to workaround a [bug](https://github.com/Microsoft/vscode/issues/45590) in VSC.
- I actually bumped the minimum engine version.
- I added the new `terminal.env` setting in `package.json`
- You were extending the env in the wrong order (a terminal's env should overwrite the global env, not the other way around).
- Renamed `applyGobalEnv` to `envInherit`, when we'll have support for [groups](https://github.com/fabiospampinato/vscode-terminals/issues/12) this name would make more sense.

Thanks again for your PR, feel welcome to submit another one in the future.

**Comment by M-Zuber** [comment]
Awesome!
Thank you for taking the time to write this up for me

> I actually bumped the minimum engine version.

oops..

**Pull request merged**
